import type { EmpresaComIndicadores, EmpresaListaResponse } from '../../types/empresa';

const mockEmpresas: EmpresaComIndicadores[] = [
    {
        id: 1,
        id_ej: 101,
        nome: 'Consult Jr.',
        cluster: 4,
        comunidade: 'CAPIBA',
        status: 'FEDERADA',
        foto_url: null,
        cidade: 'Recife',
        universidade: 'UFPE',
        faturamento_acumulado: 85000,
        faturamento_colab_acumulado: 12000,
        faturamento_mes: 15000,
        projetos_totais: 14,
        projetos_colab_totais: 3,
        csat_medio: 0.9,
        percentual_meta: 72.0,
        ritmo: 'significativo',
        taxa_colaboracao: 0.14,
        pontos_cluster: 68000000,
        cluster_calculado: 4,
        tendencia_cluster: 'sobe',
    },
    {
        id: 2,
        id_ej: 102,
        nome: 'Ecos Jr.',
        cluster: 3,
        comunidade: 'CAPIBA',
        status: 'FEDERADA',
        foto_url: null,
        cidade: 'Recife',
        universidade: 'UNICAP',
        faturamento_acumulado: 45000,
        faturamento_colab_acumulado: 8000,
        faturamento_mes: 8000,
        projetos_totais: 8,
        projetos_colab_totais: 2,
        csat_medio: 0.8,
        percentual_meta: 55.0,
        ritmo: 'minimo',
        taxa_colaboracao: 0.18,
        pontos_cluster: 30000000,
        cluster_calculado: 3,
        tendencia_cluster: 'mantem',
    },
    {
        id: 3,
        id_ej: 103,
        nome: 'Terra Jr.',
        cluster: 2,
        comunidade: 'TROPICANA',
        status: 'FEDERADA',
        foto_url: null,
        cidade: 'Caruaru',
        universidade: 'UFPE',
        faturamento_acumulado: 22000,
        faturamento_colab_acumulado: 3500,
        faturamento_mes: 4500,
        projetos_totais: 5,
        projetos_colab_totais: 1,
        csat_medio: 0.5,
        percentual_meta: 30.0,
        ritmo: 'minimo',
        taxa_colaboracao: 0.16,
        pontos_cluster: 15000000,
        cluster_calculado: 2,
        tendencia_cluster: 'mantem',
    },
    {
        id: 4,
        id_ej: 104,
        nome: 'Arcos Consultoria',
        cluster: 5,
        comunidade: 'PRAIEIRA',
        status: 'FEDERADA',
        foto_url: null,
        cidade: 'Petrolina',
        universidade: 'UNIVASF',
        faturamento_acumulado: 180000,
        faturamento_colab_acumulado: 35000,
        faturamento_mes: 32000,
        projetos_totais: 22,
        projetos_colab_totais: 6,
        csat_medio: 1.0,
        percentual_meta: 91.0,
        ritmo: 'significativo',
        taxa_colaboracao: 0.19,
        pontos_cluster: 145000000,
        cluster_calculado: 5,
        tendencia_cluster: 'sobe',
    },
    {
        id: 5,
        id_ej: 105,
        nome: 'Nexus Engenharia',
        cluster: 1,
        comunidade: 'TROPICANA',
        status: 'FEDERADA',
        foto_url: null,
        cidade: 'Garanhuns',
        universidade: 'UPE',
        faturamento_acumulado: 5000,
        faturamento_colab_acumulado: 0,
        faturamento_mes: 0,
        projetos_totais: 1,
        projetos_colab_totais: 0,
        csat_medio: null,
        percentual_meta: 5.0,
        ritmo: 'sem_vendas',
        taxa_colaboracao: 0,
        pontos_cluster: 3000000,
        cluster_calculado: 1,
        tendencia_cluster: 'desce',
    },
    {
        id: 6,
        id_ej: 106,
        nome: 'Vértice Jr.',
        cluster: 3,
        comunidade: 'PRAIEIRA',
        status: 'FEDERADA',
        foto_url: null,
        cidade: 'Recife',
        universidade: 'UPE',
        faturamento_acumulado: 52000,
        faturamento_colab_acumulado: 10000,
        faturamento_mes: 9500,
        projetos_totais: 10,
        projetos_colab_totais: 2,
        csat_medio: 0.5,
        percentual_meta: 62.0,
        ritmo: 'significativo',
        taxa_colaboracao: 0.19,
        pontos_cluster: 42000000,
        cluster_calculado: 3,
        tendencia_cluster: 'sobe',
    },
];

export const mockEmpresaListaResponse: EmpresaListaResponse = {
    data: mockEmpresas,
    meta: {
        page: 1,
        page_size: 20,
        total: mockEmpresas.length,
        total_pages: 1,
    },
};
